### ISSUE TITLE
Pretty strange problem (keyboard fades out)

### ISSUE THREAD

**Issue by alex9099** [VladThodo/behe-keyboard#15] opened 2017-08-16 12:29 UTC
hi,

I downloaded behe keyboard from fdroid, it has a lot of potential, i liked it, but i'm now using hackers keyboard because of three issues:

-If i'm writing *very* fast and touch two fingers on the keyboard, it switches to arrows mode

-Not sure if there is some key that does this, the keyboard starts fading but it continues open, clicking on text box sometimes brings the keyboard back

-~~i cant open settings for the keyboard because it crashes system settings~~ (nvm, this was because i had google keyboard disabled)

I'm on lolipop 5.1, with a bq aquaris e5 fhd

**Comment by rosariotech** [comment] 2017-08-17 19:48
Same here. I liked the keyboard for being simple and lightweight, but it keeps being transparent.

lineage 14 (android 7.1.2) - moto g4 play

**Comment by VladThodo** [comment] 2017-08-17 20:15
Any way to reproduce this issue? I never experienced this,and it seems like a serious issue.

**Comment by mtbu** [comment] 2017-08-17 21:03
Swiping from left to right on the keyboard seems to reproduce this for me, sometimes typing fast does this too (maybe it's picked up as a swipe gesture)

**Comment by mtbu** [comment] 2017-08-17 21:06
I was using the fdroid version (1.0.2) as well

**Comment by alex9099** [comment] 2017-08-18 00:46
The crashing problem seems to be because i had google keyboard disabled (for some reason android does not deal very well with disabled keyboard)

The fading thing happens if i type pretty fast and sometimes if i switch  "mode"

**Comment by rosariotech** [comment] 2017-08-18 11:53
I tried to record in this video: https://youtu.be/hW7qinWEG-g

**Comment by VladThodo** [comment] 2017-08-19 13:48
It seems it was my fault. I've accidentally uploaded some testing code, that's why the issue was never present to the Google Play version, only on F-Droid. It was detecting the swipe and playing an animation. I fixed it now by  b0cf62c. The switch to arrow mode bug was also due to the swipe. Update the app, test it and tell me if there's any other problem that you find. Thanks!

**Comment by noxarivis** [comment] 2017-08-24 11:18
that was the issue mentioned by me first

**Comment by noxarivis** [comment] 2017-08-24 11:25
it seems to be fixed...

I recommend closing this issue

**Closed** 2018-02-01 10:46 UTC
